"use client"

/**
 * Provides the main role-aware timesheet workspace and navigation.
 *
 * This client component owns the visible application state after authentication:
 * loaded entries, current tab, sync errors, and optimistic edit behavior. It also
 * translates the user's role into visible navigation choices so the UI matches
 * the permissions enforced by the API routes.
 */
import { useEffect, useState } from "react"
import { EmployeeWorkspace } from "@/components/employee-workspace"
import { EmployeeRightsPanel, MessagesPanel } from "@/components/collaboration-panel"
import { notifyPermissionsChanged } from "@/lib/permission-events"
import { EntryReviewDialog, ManagerWorkspace } from "@/components/manager-workspace"
import { permissionLabels, resolvePermissions, type Permission, type PermissionOverrides } from "@/lib/permissions"
import { AdminWorkspace } from "@/components/admin-workspace"
import { SecurityRiskWindow } from "@/components/security-risk-window"
import { useDialogFocus } from "@/components/use-dialog-focus"
import {
  Activity,
  BarChart3,
  CheckCircle2,
  Clock3,
  ListChecks,
  MessageSquare,
  KeyRound,
  Maximize2,
  Minimize2,
  Pencil,
  Save,
  Send,
  ShieldCheck,
  UserPlus,
  Users,
  X,
  XCircle,
} from "lucide-react"
import { AccountProfile } from "@/components/account-profile"
import { NoteInput } from "@/components/note-input"
import { EntriesLog } from "@/components/entries-log"
import { ManagerReport } from "@/components/manager-report"
import { SignOutButton } from "@/components/sign-out-button"
import { Button } from "@/components/ui/button"
import { apiPath } from "@/lib/paths"
import type {
  AccessStatus,
  EntryStatus,
  ParsedEntry,
  TimeEntry,
  UserRole,
} from "@/lib/types"

type View = "log" | "approvals" | "report" | "admin" | "messages" | "permissions"

const manageableRoles: UserRole[] = ["admin", "manager", "employee", "user"]
const manageableStatuses: AccessStatus[] = ["active", "denied", "blocked"]

/**
 * User directory row returned by the administrator users API.
 *
 * The row combines env-configured access information with persisted profile and
 * timesheet activity so admins can audit both permission state and product usage.
 */
type AdminDirectoryUser = {
  permissions?: PermissionOverrides
  /** Normalized user email shown as the stable identity. */
  email: string
  /** Effective role from environment-backed access policy. */
  role: UserRole | "none"
  /** Current access state for this user. */
  accessStatus: AccessStatus | "observed"
  /** Source of the user's visible access state. */
  accessSource: "managed" | "environment" | "observed"
  /** Whether the email is explicitly present in an access environment variable. */
  accessConfigured: boolean
  /** Optional administrator note explaining managed access decisions. */
  note: string
  /** Administrator who last updated managed access. */
  updatedBy: string | null
  /** ISO timestamp for the last managed access update. */
  updatedAt: string | null
  /** Persisted profile display name, when available. */
  displayName: string
  /** Persisted profile image data URL, when available. */
  imageDataUrl: string | null
  /** Total entries owned by the user. */
  totalEntries: number
  /** Owned entries still in draft. */
  draftEntries: number
  /** Owned entries waiting for manager review. */
  submittedEntries: number
  /** Owned entries approved by a manager or admin. */
  approvedEntries: number
  /** Owned entries rejected by a manager or admin. */
  rejectedEntries: number
  /** ISO timestamp for the user's most recently created entry. */
  lastEntryAt: string | null
}

/**
 * Draft state for the admin access editor window.
 *
 * Admins change this state with buttons and inputs inside the modal. Nothing is
 * persisted until the Save button calls the user-management API.
 */
type AccessEditorState = {
  permissions?: PermissionOverrides
  /** Whether the editor is creating a new row or changing an existing user. */
  mode: "add" | "edit"
  /** Email being created or edited. */
  email: string
  /** Draft role selected by the admin. */
  role: UserRole
  /** Draft permission state selected by the admin. */
  accessStatus: AccessStatus
  /** Draft note explaining the role or permission decision. */
  note: string
}

/**
 * Security audit event returned by the administrator audit API.
 *
 * Events are append-only server records of sensitive actions. Metadata is compact
 * by design so the audit log identifies what changed without duplicating private
 * entry descriptions or profile image payloads.
 */
type AdminAuditEvent = {
  /** Stable audit event id generated by the database. */
  id: string
  /** Email of the signed-in actor who performed the action. */
  actorEmail: string
  /** Machine-readable action label. */
  action: string
  /** Type of entity affected by the action. */
  targetType: string
  /** Optional id of the affected entity. */
  targetId: string | null
  /** Sanitized contextual data about the action. */
  metadata: Record<string, unknown>
  /** Request IP address when available. */
  ipAddress: string | null
  /** Request user agent when available. */
  userAgent: string | null
  /** ISO timestamp for when the event occurred. */
  occurredAt: string
}

/**
 * Coordinates the signed-in user's role-aware timesheet workspace.
 *
 * The app receives the effective role from the server-rendered page and uses it
 * to decide which tabs, descriptions, and bulk actions to expose. Data mutations
 * still go through the API, so this component improves ergonomics without being
 * the source of authorization truth.
 *
 * @param props - Role and signed-in user identity for the current session.
 * @param props.role - Effective role used to choose visible navigation.
 * @param props.userName - Display name from Microsoft authentication.
 * @param props.userEmail - Email from Microsoft authentication.
 * @returns The interactive timesheet application shell.
 */
export function TimesheetApp({
  role: initialRole,
  userName,
  userEmail,
}: {
  role: UserRole
  userName?: string | null
  userEmail?: string | null
}) {
  const [role,setRole] = useState(initialRole)
  const [permissions,setPermissions] = useState(() => resolvePermissions(null))
  const [accessDenied,setAccessDenied] = useState(false)
  const [permissionsLoaded,setPermissionsLoaded] = useState(false)
  const [entries, setEntries] = useState<TimeEntry[]>([])
  const [view, setView] = useState<View>(role === "admin" ? "admin" : role === "manager" ? "approvals" : "log")
  const [loadingEntries, setLoadingEntries] = useState(true)
  const [syncError, setSyncError] = useState<string | null>(null)
  const [personalStatus, setPersonalStatus] = useState<EntryStatus | "all">("all")
  const [suggestedReview,setSuggestedReview] = useState<{entry:TimeEntry;decision:"approved"|"rejected";reason:string}|null>(null)
  const [technologyReports,setTechnologyReports] = useState(false)

  useEffect(() => {
    const controller = new AbortController()
    /**
     * Refreshes server rights and role after admin saves or browser focus changes.
     * @returns Promise<void> after live authorization state is applied.
     */
    async function refreshPermissions(): Promise<void> {
      try {
        const response = await fetch(apiPath("/api/permissions"),{cache:"no-store",signal:controller.signal})
        const data = await response.json()
        if (!response.ok || !data.role) {
          setPermissionsLoaded(true); setAccessDenied(true); setPermissions(resolvePermissions(null)); setEntries([]); return
        }
        setPermissionsLoaded(true); setAccessDenied(false); setRole(data.role); setPermissions(data.permissions)
      } catch { if (!controller.signal.aborted) { setAccessDenied(true); setEntries([]); setPermissions(resolvePermissions(null)) } }
    }
    void refreshPermissions()
    const timer = window.setInterval(refreshPermissions,15000)
    window.addEventListener("focus",refreshPermissions)
    window.addEventListener("permissions-changed",refreshPermissions)
    const channel=typeof BroadcastChannel !== "undefined" ? new BroadcastChannel("permissions-changed") : null
    if(channel)channel.onmessage=()=>void refreshPermissions()
    return () => { controller.abort(); window.clearInterval(timer); window.removeEventListener("focus",refreshPermissions); window.removeEventListener("permissions-changed",refreshPermissions); channel?.close() }
  },[])

  useEffect(() => {
    if (accessDenied) return
    let active = true

    /**
     * Loads saved entries visible to the signed-in user's role.
     *
     * The API decides whether the caller receives personal entries or team-wide
     * entries. The local active flag prevents state updates after unmounting while
     * the request is still in flight.
     *
     * @returns A promise that resolves after entries are loaded or an error is stored.
     */
    async function loadEntries() {
      try {
        const res = await fetch(apiPath("/api/entries"), { cache: "no-store" })
        const data = await res.json()
        if (!res.ok) throw new Error(data.error ?? "Failed to load entries.")
        if (active) setEntries(data.entries ?? [])
      } catch (err) {
        if (active) {
          setSyncError(
            err instanceof Error ? err.message : "Failed to load entries.",
          )
        }
      } finally {
        if (active) setLoadingEntries(false)
      }
    }

    loadEntries()

    return () => {
      active = false
    }
  }, [role,permissions.view_team,accessDenied])

  const canViewTeamReports = permissions.view_reports
  const canViewAdmin = role === "admin" && !accessDenied
  const canClearVisibleEntries = permissions.delete_entries && permissions.view_team
  const canReviewEntries = permissions.review_entries
  const canSubmitEntries = permissions.submit_entries
  useEffect(() => {
    if (!canReviewEntries) setSuggestedReview(null)
  },[canReviewEntries])
  const roleLabel = {
    admin: "Administrator",
    manager: "Manager",
    employee: "Employee",
    user: "User",
  }[role]

  useEffect(() => {
    if (!permissionsLoaded) return
    if (view === "report" && !canViewTeamReports) setView("log")
    if (view === "approvals" && !canReviewEntries) setView("log")
    if (view === "admin" && !canViewAdmin) setView("log")
    if (view === "permissions" && (!permissions.delegate_permissions || (role !== "admin" && role !== "manager"))) setView("log")
    if (accessDenied && view === "messages") setView("log")
  }, [canReviewEntries, canViewAdmin, canViewTeamReports, view,permissionsLoaded,permissions.delegate_permissions,role,accessDenied])

  /**
   * Persists newly parsed entries and prepends them to the local view.
   *
   * Parsed entries come from the note input and do not have ids yet. The API
   * stores them under the current user and returns database-backed entries that
   * can be edited or deleted immediately.
   *
   * @param parsed - Entries returned by the AI parser.
   * @returns A promise that resolves after entries are saved and local state updates.
   */
  async function addParsed(parsed: ParsedEntry[]) {
    const res = await fetch(apiPath("/api/entries"), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ entries: parsed }),
    })
    const data = await res.json()
    if (!res.ok) throw new Error(data.error ?? "Failed to save entries.")
    setEntries((prev) => [...(data.entries ?? []), ...prev])
    setSyncError(null)
  }

  /**
   * Optimistically updates one entry and rolls back if the API rejects it.
   *
   * The user sees edits immediately while the PATCH request runs. If the backend
   * rejects the change because of validation, permissions, or connectivity, the
   * previous entry list is restored and a sync error is shown.
   *
   * @param id - Entry id to update.
   * @param patch - Partial entry fields to apply.
   * @returns Nothing; local state and API sync happen as side effects.
   */
  function updateEntry(id: string, patch: Partial<TimeEntry>) {
    const previous = entries
    setEntries((prev) =>
      prev.map((e) => (e.id === id ? { ...e, ...patch } : e)),
    )

    fetch(apiPath(`/api/entries/${id}`), {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    })
      .then(async (res) => {
        const data = await res.json()
        if (!res.ok) throw new Error(data.error ?? "Failed to update entry.")
        setEntries((prev) =>
          prev.map((e) => (e.id === id ? data.entry : e)),
        )
        setSyncError(null)
      })
      .catch((err) => {
        setEntries(previous)
        setSyncError(
          err instanceof Error ? err.message : "Failed to update entry.",
        )
      })
  }

  /**
   * Moves one entry through the approval workflow.
   *
   * Status updates share the same optimistic update path as field edits.
   * Employees use this to submit draft or rejected rows, while managers and
   * administrators use it to approve or reject submitted rows.
   *
   * @param id - Entry id whose approval status should change.
   * @param status - New approval status to persist.
   * @param reviewNote - Optional manager rejection note.
   * @returns Nothing; local state and API sync happen as side effects.
   */
  function changeEntryStatus(
    id: string,
    status: EntryStatus,
    reviewNote?: string,
  ) {
    updateEntry(id, { status, reviewNote })
  }

  /**
   * Optimistically removes one entry and restores it if deletion fails.
   *
   * Deletion follows the same optimistic pattern as editing. The API still checks
   * ownership and role scope, so a locally visible row cannot be removed unless
   * the server confirms permission.
   *
   * @param id - Entry id to delete.
   * @returns Nothing; local state and API sync happen as side effects.
   */
  function deleteEntry(id: string) {
    const previous = entries
    setEntries((prev) => prev.filter((e) => e.id !== id))

    fetch(apiPath(`/api/entries/${id}`), { method: "DELETE" })
      .then(async (res) => {
        const data = await res.json()
        if (!res.ok) throw new Error(data.error ?? "Failed to delete entry.")
        setSyncError(null)
      })
      .catch((err) => {
        setEntries(previous)
        setSyncError(
          err instanceof Error ? err.message : "Failed to delete entry.",
        )
      })
  }

  /**
   * Clears every entry visible to the signed-in user's role.
   *
   * This action is only exposed to managers and administrators. The backend uses
   * the same role information to decide whether "visible" means team-wide data or
   * the current user's own entries.
   *
   * @returns Nothing; local state and API sync happen as side effects.
   */
  function clearEntries() {
    const previous = entries
    setEntries([])

    fetch(apiPath("/api/entries"), { method: "DELETE" })
      .then(async (res) => {
        const data = await res.json()
        if (!res.ok) throw new Error(data.error ?? "Failed to clear entries.")
        setSyncError(null)
      })
      .catch((err) => {
        setEntries(previous)
        setSyncError(
          err instanceof Error ? err.message : "Failed to clear entries.",
        )
      })
  }

  const totalHours = entries.reduce((s, e) => s + (Number(e.hours) || 0), 0)
  const pendingEntries = entries.filter((entry) => entry.status === "submitted")
  const approvedEntries = entries.filter((entry) => entry.status === "approved")
  const rejectedEntries = entries.filter((entry) => entry.status === "rejected")
  const draftEntries = entries.filter((entry) => entry.status === "draft")

  const tabs: { key: View; label: string; icon: typeof ListChecks }[] = [
    {
      key: "log",
      label: permissions.view_team ? "Team entries" : "My entries",
      icon: ListChecks,
    },
    ...(canReviewEntries
      ? [{ key: "approvals" as const, label: "Approvals", icon: CheckCircle2 }]
      : []),
    ...(canViewTeamReports
      ? [{ key: "report" as const, label: "Reports", icon: BarChart3 }]
      : []),
    ...(canViewAdmin
      ? [{ key: "admin" as const, label: "Admin", icon: ShieldCheck }]
      : []),
    ...(!accessDenied ? [{key:"messages" as const,label:"Messages",icon:MessageSquare}] : []),
    ...(permissions.delegate_permissions && (role === "admin" || role === "manager") ? [{key:"permissions" as const,label:"Employee rights",icon:KeyRound}] : []),
  ]

  return (
    <main className="mx-auto flex min-h-svh w-full max-w-[1600px] flex-col gap-6 px-4 py-8 md:px-8 md:py-12">
      <header className="flex flex-col gap-1">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-center gap-2 text-primary">
            <Clock3 className="size-5" aria-hidden="true" />
            <span className="text-xs font-semibold uppercase tracking-widest">
              Timesheet
            </span>
          </div>
          <div className="flex min-w-0 items-center justify-end gap-3">
            <AccountProfile
              email={userEmail}
              fallbackName={userName}
              role={roleLabel}
            />
            <SignOutButton />
          </div>
        </div>
        <h1 className="text-2xl font-semibold tracking-tight text-balance md:text-3xl">
          Contractor hours, from messy notes to a manager report
        </h1>
        <p className="max-w-2xl text-sm text-muted-foreground text-pretty">
          Paste time-worked notes in any format. AI extracts structured entries you
          can review and edit, then rolls them into a clean report of hours per
          contractor.
        </p>
      </header>

      <details open={role !== "admin"} className="border-b border-border pb-2">
        <summary className="cursor-pointer text-sm font-medium">Workspace overview</summary>
        <RoleOverview role={role} />
      </details>
      {canViewAdmin && <AdminWorkspace onDirectory={() => setView("admin")} onSecurity={() => setTechnologyReports(true)} />}
      {canViewAdmin && technologyReports && <SecurityRiskWindow onClose={() => setTechnologyReports(false)} />}

      <details open={role !== "admin"} className="border-b border-border pb-2">
      <summary className="cursor-pointer text-sm font-medium">Workflow totals</summary>
      <WorkflowOverview
        approvedCount={approvedEntries.length}
        draftCount={draftEntries.length}
        pendingCount={pendingEntries.length}
        rejectedCount={rejectedEntries.length}
        role={role}
      />

      </details>
      {permissions.create_entries && <details open={role === "employee" || role === "user"} className="border-b border-border pb-2"><summary className="cursor-pointer text-sm font-medium">Add time entries</summary><NoteInput onParsed={addParsed} /></details>}
      {(role === "employee" || role === "user") && <EmployeeWorkspace entries={entries} selected={personalStatus} onSelect={setPersonalStatus} />}
      {!accessDenied && (canReviewEntries || permissions.ai_review || canViewTeamReports) && <ManagerWorkspace canReview={canReviewEntries} canReports={canViewTeamReports} canAI={permissions.ai_review} pending={pendingEntries.length} entries={pendingEntries} onApprovals={() => setView("approvals")} onReports={() => setView("report")} onRecommendation={(entry,decision,reason) => setSuggestedReview({entry,decision,reason})} />}
      {suggestedReview && <EntryReviewDialog entry={suggestedReview.entry} decision={suggestedReview.decision} initialNote={suggestedReview.reason} onCancel={() => setSuggestedReview(null)} onConfirm={note => {
        changeEntryStatus(suggestedReview.entry.id,suggestedReview.decision,note || undefined)
        setSuggestedReview(null)
      }} />}
      {accessDenied && <p role="alert">Access is unavailable. Contact your administrator.</p>}

      {(loadingEntries || syncError) && (
        <div
          className={`rounded-lg border px-4 py-3 text-sm ${
            syncError
              ? "border-destructive/40 bg-destructive/10 text-destructive"
              : "border-border bg-muted/50 text-muted-foreground"
          }`}
          role={syncError ? "alert" : "status"}
        >
          {syncError ?? "Loading saved entries..."}
        </div>
      )}

      {/* View switch */}
      <div aria-label="Workspace views" className="sticky top-0 z-10 grid grid-cols-2 gap-1 rounded-lg border border-border bg-card p-1 shadow-sm sm:flex sm:items-center">
        {tabs.map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            type="button"
            onClick={() => setView(key)}
            aria-pressed={view === key}
            className={`flex min-w-0 flex-1 items-center justify-center gap-2 rounded-md px-2 py-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${
              view === key
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <Icon className="size-4" aria-hidden="true" />
            {label}
            {key === "log" && entries.length > 0 && (
              <span
                className={`ml-1 rounded-full px-1.5 text-xs tabular-nums ${
                  view === key
                    ? "bg-primary-foreground/20"
                    : "bg-muted-foreground/15"
                }`}
              >
                {entries.length}
              </span>
            )}
            {key === "approvals" && pendingEntries.length > 0 && (
              <span
                className={`ml-1 rounded-full px-1.5 text-xs tabular-nums ${
                  view === key
                    ? "bg-primary-foreground/20"
                    : "bg-muted-foreground/15"
                }`}
              >
                {pendingEntries.length}
              </span>
            )}
          </button>
        ))}
      </div>

      {view === "log" ? (
        <EntriesLog
          entries={(role === "employee" || role === "user") && personalStatus !== "all" ? entries.filter(entry => entry.status === personalStatus) : entries}
          onUpdate={updateEntry}
          onStatusChange={changeEntryStatus}
          onDelete={deleteEntry}
          onClear={clearEntries}
          canClear={canClearVisibleEntries}
          canReview={canReviewEntries}
          canSubmit={canSubmitEntries}
          canEdit={permissions.edit_entries}
          canDelete={permissions.delete_entries}
          description={
            permissions.view_team
              ? "Review, edit, and manage team entries for your role."
              : "Review, edit, and submit your own saved time entries."
          }
          title={permissions.view_team ? "Team entries" : "My time entries"}
        />
      ) : view === "approvals" ? (
        pendingEntries.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border bg-card/50 px-6 py-16 text-center">
            <p className="text-sm font-medium">No entries waiting for approval</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Submitted time will appear here for manager review.
            </p>
          </div>
        ) : (
          <EntriesLog
            entries={pendingEntries}
            onUpdate={updateEntry}
            onStatusChange={changeEntryStatus}
            onDelete={deleteEntry}
            onClear={clearEntries}
            canClear={false}
            canReview={canReviewEntries}
            canSubmit={false}
            canEdit={permissions.edit_entries}
            canDelete={permissions.delete_entries}
            description="Approve or reject submitted time after review."
            title="Pending approvals"
          />
        )
      ) : view === "report" ? (
        entries.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border bg-card/50 px-6 py-16 text-center">
            <p className="text-sm font-medium">Nothing to report yet</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Add some entries first and the manager report will build itself.
            </p>
          </div>
        ) : (
          <ManagerReport entries={entries} />
        )
      ) : view === "messages" ? (
        <MessagesPanel canSend={permissions.send_messages && (role === "admin" || role === "manager")} />
      ) : view === "permissions" ? (
        <EmployeeRightsPanel permissions={permissions} />
      ) : (
        <AdminPanel role={role} />
      )}

      <footer className="mt-auto pt-4 text-center text-xs text-muted-foreground">
        {entries.length} entries ·{" "}
        {totalHours.toLocaleString(undefined, { maximumFractionDigits: 2 })}h logged
        this session · {approvedEntries.length} approved · data is saved to Neon
      </footer>
    </main>
  )
}

/**
 * Shows the active role and what that role can do.
 *
 * The panel is intentionally informational: it helps the signed-in user understand
 * why they see a personal log, team report, or admin controls. Permission checks
 * remain enforced in the API layer.
 *
 * @param props - Component props.
 * @param props.role - Effective role for the signed-in user.
 * @returns A role summary panel.
 */
function RoleOverview({ role }: { role: UserRole }) {
  const content = {
    admin: {
      title: "Admin access",
      body: "You can view all entries, approve or reject submitted time, use reports, and access admin controls.",
    },
    manager: {
      title: "Manager access",
      body: "You can review submitted time, approve or reject entries, and build team reports.",
    },
    employee: {
      title: "Employee access",
      body: "You can create, edit, and submit your own time entries for manager approval.",
    },
    user: {
      title: "User access",
      body: "You can create and submit your own time entries for review.",
    },
  }[role]

  return (
    <section className="rounded-lg border border-border bg-card px-4 py-3 shadow-sm">
      <p className="text-sm font-medium">{content.title}</p>
      <p className="mt-1 text-xs text-muted-foreground">{content.body}</p>
    </section>
  )
}

/**
 * Shows a compact status dashboard for the current role's visible entries.
 *
 * Counts are derived from the same entry list used by the active table and report
 * views, so employees see their own progress while managers see team workflow load.
 *
 * @param props - Workflow summary counts and current user role.
 * @param props.approvedCount - Number of visible approved entries.
 * @param props.draftCount - Number of visible draft entries.
 * @param props.pendingCount - Number of visible submitted entries.
 * @param props.rejectedCount - Number of visible rejected entries.
 * @param props.role - Effective role for the signed-in user.
 * @returns A role-aware workflow status summary.
 */
function WorkflowOverview({
  approvedCount,
  draftCount,
  pendingCount,
  rejectedCount,
  role,
}: {
  approvedCount: number
  draftCount: number
  pendingCount: number
  rejectedCount: number
  role: UserRole
}) {
  const reviewLabel =
    role === "admin" || role === "manager"
      ? "Waiting for your review"
      : "Waiting for manager review"

  const items = [
    { label: "Draft", value: draftCount, icon: ListChecks },
    { label: reviewLabel, value: pendingCount, icon: Send },
    { label: "Approved", value: approvedCount, icon: CheckCircle2 },
    { label: "Rejected", value: rejectedCount, icon: XCircle },
  ]

  return (
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
      {items.map(({ label, value, icon: Icon }) => (
        <div
          key={label}
          className="rounded-lg border border-border bg-card px-3 py-3 shadow-sm"
        >
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Icon className="size-3.5" aria-hidden="true" />
            <span>{label}</span>
          </div>
          <p className="mt-2 font-mono text-2xl font-semibold tabular-nums">
            {value}
          </p>
        </div>
      ))}
    </section>
  )
}

/**
 * Shows administrators the users known to the app and access configuration.
 *
 * The panel combines environment configuration, admin-managed access rows, and
 * observed product activity. It orders people by seniority and forces role or
 * permission edits through an explicit editor window and Save action.
 *
 * @param props - Admin panel props.
 * @param props.role - Effective role for the signed-in user.
 * @returns The administrator user directory panel, or null for non-admin roles.
 */
function AdminPanel({ role }: { role: UserRole }) {
  const [users, setUsers] = useState<AdminDirectoryUser[]>([])
  const [auditEvents, setAuditEvents] = useState<AdminAuditEvent[]>([])
  const [allActivityEvents, setAllActivityEvents] = useState<AdminAuditEvent[]>([])
  const [activityWindowOpen, setActivityWindowOpen] = useState(false)
  const [activityLoading, setActivityLoading] = useState(false)
  const [activityError, setActivityError] = useState<string | null>(null)
  const [accessEditor, setAccessEditor] = useState<AccessEditorState | null>(
    null,
  )
  const [savingUser, setSavingUser] = useState<string | null>(null)
  const [managementError, setManagementError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let active = true

    if (role !== "admin") {
      setLoading(false)
      return () => {
        active = false
      }
    }

    /**
     * Loads administrator directory and audit data from the server.
     *
     * The APIs enforce admin-only access. Directory data supports operational
     * access review, while audit data supports security investigation.
     *
     * @returns A promise that resolves after admin data loads or an error is stored.
     */
    async function loadAdminData() {
      try {
        const [usersRes, auditRes] = await Promise.all([
          fetch(apiPath("/api/users"), { cache: "no-store" }),
          fetch(apiPath("/api/audit?limit=25"), { cache: "no-store" }),
        ])
        const usersData = await usersRes.json()
        const auditData = await auditRes.json()
        if (!usersRes.ok) {
          throw new Error(usersData.error ?? "Failed to load users.")
        }
        if (!auditRes.ok) {
          throw new Error(auditData.error ?? "Failed to load audit events.")
        }
        if (active) {
          setUsers(sortAdminDirectoryUsers(usersData.users ?? []))
          setAuditEvents(auditData.events ?? [])
        }
      } catch (err) {
        if (active) {
          setError(
            err instanceof Error ? err.message : "Failed to load admin data.",
          )
        }
      } finally {
        if (active) setLoading(false)
      }
    }

    loadAdminData()

    return () => {
      active = false
    }
  }, [role])

  if (role !== "admin") {
    return null
  }

  const configuredCount = users.filter((user) => user.accessConfigured).length
  const submittedCount = users.reduce(
    (sum, user) => sum + user.submittedEntries,
    0,
  )
  const sortedUsers = sortAdminDirectoryUsers(users)

  /**
   * Applies a saved managed access assignment to the visible directory.
   *
   * The user-management API returns the saved access row, not the full directory
   * summary. This helper preserves any activity counts already loaded for that
   * email while updating role, status, note, and source fields.
   *
   * @param managedUser - Saved managed access row returned by the API.
   * @returns Nothing; directory state is updated as a side effect.
   */
  function applyManagedAccessUser(managedUser: {
    permissions?: PermissionOverrides
    email: string
    role: UserRole
    accessStatus: AccessStatus
    note: string
    updatedBy: string | null
    updatedAt: string | null
  }) {
    setUsers((previous) => {
      const normalizedEmail = managedUser.email.toLowerCase()
      const existing = previous.find((user) => user.email === normalizedEmail)
      const nextUser: AdminDirectoryUser = {
        email: normalizedEmail,
        role: managedUser.role,
        accessStatus: managedUser.accessStatus,
        accessSource: "managed",
        accessConfigured: true,
        note: managedUser.note,
        permissions: managedUser.permissions ?? {},
        updatedBy: managedUser.updatedBy,
        updatedAt: managedUser.updatedAt,
        displayName: existing?.displayName ?? "",
        imageDataUrl: existing?.imageDataUrl ?? null,
        totalEntries: existing?.totalEntries ?? 0,
        draftEntries: existing?.draftEntries ?? 0,
        submittedEntries: existing?.submittedEntries ?? 0,
        approvedEntries: existing?.approvedEntries ?? 0,
        rejectedEntries: existing?.rejectedEntries ?? 0,
        lastEntryAt: existing?.lastEntryAt ?? null,
      }
      const withoutUser = previous.filter((user) => user.email !== normalizedEmail)
      return sortAdminDirectoryUsers([...withoutUser, nextUser])
    })
  }

  /**
   * Saves a managed access assignment through the admin users API.
   *
   * This function is only called by the editor window's Save button. Successful
   * changes are reflected immediately and audited server-side by the API route.
   *
   * @param payload - Access assignment values to persist.
   * @returns True when the assignment is saved, otherwise false.
   */
  async function saveManagedUserAccess(payload: {
    permissions?: PermissionOverrides
    email: string
    role: UserRole
    accessStatus: AccessStatus
    note?: string
  }) {
    setSavingUser(payload.email.toLowerCase())
    setManagementError(null)

    try {
      const res = await fetch(apiPath("/api/users"), {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error ?? "Failed to save user access.")
      }
      applyManagedAccessUser(data.user)
      notifyPermissionsChanged()
      return true
    } catch (err) {
      setManagementError(
        err instanceof Error ? err.message : "Failed to save user access.",
      )
      return false
    } finally {
      setSavingUser(null)
    }
  }

  /**
   * Opens the dynamic access editor for a new employee record.
   *
   * @returns Nothing; editor state is prepared for a new managed user.
   */
  function openAddUserEditor() {
    setManagementError(null)
    setAccessEditor({
      mode: "add",
      email: "",
      role: "employee",
      accessStatus: "active",
      note: "",
    })
  }

  /**
   * Opens the dynamic access editor for an existing directory row.
   *
   * Observed users do not have a saved permission state yet, so the editor starts
   * them as active employees until the admin chooses a different role or status.
   *
   * @param user - Directory row to edit.
   * @returns Nothing; editor state is prepared from the selected user.
   */
  function openEditUserEditor(user: AdminDirectoryUser) {
    setManagementError(null)
    setAccessEditor({
      mode: "edit",
      email: user.email,
      role: user.role === "none" ? "employee" : user.role,
      accessStatus:
        user.accessStatus === "observed" ? "active" : user.accessStatus,
      note: user.note,
      permissions: user.permissions ?? {},
    })
  }

  /**
   * Saves the current editor draft through the admin users API.
   *
   * The Save button is the only UI path that persists role or permission changes.
   * The modal remains open when validation or the server rejects the request.
   *
   * @returns A promise that resolves after the save attempt finishes.
   */
  async function saveAccessEditor() {
    if (!accessEditor || !accessEditor.email.trim()) return

    const saved = await saveManagedUserAccess({
      email: accessEditor.email.trim(),
      role: accessEditor.role,
      accessStatus: accessEditor.accessStatus,
      note: accessEditor.note.trim(),
      permissions: accessEditor.permissions,
    })

    if (saved) {
      setAccessEditor(null)
    }
  }

  /**
   * Opens the full admin activity window and loads extended audit events.
   *
   * The compact admin panel only shows a short preview. This loader fetches the
   * largest bounded audit set supported by the API so administrators can inspect
   * broader app activity without exposing the view to non-admin roles.
   *
   * @returns A promise that resolves after the activity window is populated.
   */
  async function openActivityWindow() {
    setActivityWindowOpen(true)
    setActivityError(null)

    if (allActivityEvents.length > 0) return

    setActivityLoading(true)
    try {
      const res = await fetch(apiPath("/api/audit?limit=250"), {
        cache: "no-store",
      })
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error ?? "Failed to load app activity.")
      }
      setAllActivityEvents(data.events ?? [])
    } catch (err) {
      setActivityError(
        err instanceof Error ? err.message : "Failed to load app activity.",
      )
    } finally {
      setActivityLoading(false)
    }
  }

  const activityEvents = allActivityEvents.length > 0 ? allActivityEvents : auditEvents

  return (
    <div className="flex flex-col gap-4 rounded-xl bg-white p-3 text-slate-950 shadow-sm">
      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-200 bg-white px-4 py-3">
        <div className="flex items-center gap-2">
          <ShieldCheck className="size-4 text-blue-700" aria-hidden="true" />
          <h2 className="text-sm font-semibold">Admin user directory</h2>
        </div>
        <p className="mt-1 text-xs text-slate-600">
          Admins, managers, employees, and users are ordered by seniority. Use
          Edit to change a person's role or permission state.
        </p>
      </div>

        <details className="border-b border-slate-200 px-4 py-2"><summary className="cursor-pointer text-xs font-medium">Directory totals ({users.length} users)</summary>
        <div className="grid grid-cols-1 gap-3 bg-white py-2 sm:grid-cols-3">
        <AdminStat icon={Users} label="Directory users" value={users.length} />
        <AdminStat icon={ShieldCheck} label="Configured access" value={configuredCount} />
        <AdminStat icon={CheckCircle2} label="Awaiting review" value={submittedCount} />
        </div>
        </details>

        <div className="flex flex-col gap-3 border-b border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h3 className="text-sm font-semibold">Employee access</h3>
          </div>
          <Button
            type="button"
            className="w-fit bg-blue-700 text-white hover:bg-blue-800"
            onClick={openAddUserEditor}
          >
            <UserPlus className="size-4" aria-hidden="true" />
            Add employee
          </Button>
          {managementError && (
            <p className="mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              {managementError}
            </p>
          )}
        </div>

      {loading || error ? (
        <div
          className={`m-4 rounded-lg border px-4 py-3 text-sm ${
            error
              ? "border-red-200 bg-red-50 text-red-700"
              : "border-slate-200 bg-slate-50 text-slate-600"
          }`}
          role={error ? "alert" : "status"}
        >
          {error ?? "Loading users..."}
        </div>
      ) : users.length === 0 ? (
        <div className="px-6 py-12 text-center">
          <p className="text-sm font-medium">No known users yet</p>
          <p className="mt-1 text-xs text-slate-600">
            Configured users and profile activity will appear here.
          </p>
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500">
                <th className="px-4 py-2 font-medium">User</th>
                <th className="px-4 py-2 font-medium">Role</th>
                <th className="px-4 py-2 font-medium">Permission</th>
                <th className="px-4 py-2 font-medium">Rights</th>
                <th className="px-4 py-2 text-right font-medium">Entries</th>
                <th className="px-4 py-2 text-right font-medium">Review</th>
                <th className="px-4 py-2 font-medium">Last entry</th>
                <th className="px-4 py-2 text-right font-medium">Actions</th>
              </tr>
            </thead>
            <tbody>
              {sortedUsers.map((user) => (
                <tr
                  key={user.email}
                  className="border-b border-slate-200 last:border-0"
                >
                  <td className="px-4 py-2">
                    <p className="font-medium">{user.displayName || user.email}</p>
                    {user.displayName && (
                      <p className="text-xs text-slate-500">{user.email}</p>
                    )}
                  </td>
                  <td className="px-4 py-2">
                    <span
                      className={`inline-flex rounded-full border px-2 py-0.5 text-xs font-medium capitalize ${roleBadgeClass(user.role)}`}
                    >
                      {user.role}
                    </span>
                  </td>
                  <td className="px-4 py-2">
                    <div className="flex flex-col gap-2">
                      <span
                        className={`inline-flex w-fit rounded-full border px-2 py-0.5 text-xs font-medium ${accessStatusClass(user.accessStatus)}`}
                      >
                        {user.accessSource}: {user.accessStatus}
                      </span>
                      {user.note && (
                        <p className="max-w-56 text-xs text-slate-500">
                          {user.note}
                        </p>
                      )}
                    </div>
                  </td>
                  <td className="px-4 py-2 text-xs text-slate-600">
                    {roleRights(user.role).join(" · ")}
                  </td>
                  <td className="px-4 py-2 text-right font-mono tabular-nums">
                    {user.totalEntries}
                  </td>
                  <td className="px-4 py-2 text-right font-mono text-xs tabular-nums">
                    {user.submittedEntries} pending · {user.approvedEntries} approved
                  </td>
                  <td className="px-4 py-2 text-xs text-slate-500">
                    {user.lastEntryAt ? formatAdminDate(user.lastEntryAt) : "—"}
                  </td>
                  <td className="px-4 py-2 text-right">
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
                      onClick={() => openEditUserEditor(user)}
                      disabled={savingUser === user.email}
                    >
                      <Pencil className="size-3.5" aria-hidden="true" />
                      Edit
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      </section>

      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-200 bg-white px-4 py-3">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div className="flex items-center gap-2">
                <ShieldCheck className="size-4 text-blue-700" aria-hidden="true" />
                <h2 className="text-sm font-semibold">Security audit log</h2>
              </div>
              <p className="mt-1 text-xs text-slate-600">
                Recent sensitive actions are recorded with actor, target, time,
                and request context.
              </p>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
              onClick={openActivityWindow}
            >
              <Activity className="size-3.5" aria-hidden="true" />
              View all app activity
            </Button>
          </div>
        </div>

      {loading || error ? (
        <div
          className={`m-4 rounded-lg border px-4 py-3 text-sm ${
            error
              ? "border-red-200 bg-red-50 text-red-700"
              : "border-slate-200 bg-slate-50 text-slate-600"
          }`}
          role={error ? "alert" : "status"}
        >
          {error ?? "Loading audit events..."}
        </div>
      ) : auditEvents.length === 0 ? (
        <div className="px-6 py-10 text-center">
          <p className="text-sm font-medium">No audit events yet</p>
          <p className="mt-1 text-xs text-slate-600">
            Entry, approval, deletion, and profile actions will appear here.
          </p>
        </div>
      ) : (
        <details className="px-4 py-2"><summary className="cursor-pointer text-sm font-medium">Recent activity ({auditEvents.length})</summary>
        <div className="max-h-[40dvh] overflow-auto overscroll-contain">
          <table className="w-full border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500">
                <th className="px-4 py-2 font-medium">Time</th>
                <th className="px-4 py-2 font-medium">Actor</th>
                <th className="px-4 py-2 font-medium">Action</th>
                <th className="px-4 py-2 font-medium">Target</th>
                <th className="px-4 py-2 font-medium">Context</th>
              </tr>
            </thead>
            <tbody>
              {auditEvents.map((event) => (
                <tr
                  key={event.id}
                  className="border-b border-slate-200 last:border-0"
                >
                  <td className="px-4 py-2 text-xs text-slate-500">
                    {formatAdminDateTime(event.occurredAt)}
                  </td>
                  <td className="px-4 py-2 font-medium">{event.actorEmail}</td>
                  <td className="px-4 py-2">
                    {formatAuditAction(event.action)}
                  </td>
                  <td className="px-4 py-2 text-xs text-slate-500">
                    {event.targetType}
                    {event.targetId ? ` · ${shortId(event.targetId)}` : ""}
                  </td>
                  <td className="px-4 py-2 text-xs text-slate-500">
                    {formatAuditMetadata(event)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div></details>
      )}
      </section>

      {activityWindowOpen && (
        <AdminActivityWindow
          events={activityEvents}
          error={activityError}
          loading={activityLoading}
          onClose={() => setActivityWindowOpen(false)}
        />
      )}
      {accessEditor && (
        <AdminUserAccessEditor
          editor={accessEditor}
          error={managementError}
          saving={savingUser === accessEditor.email.toLowerCase()}
          onChange={(nextEditor) => setAccessEditor(nextEditor)}
          onClose={() => {
            if (!savingUser) setAccessEditor(null)
          }}
          onSave={saveAccessEditor}
        />
      )}
    </div>
  )
}

/**
 * Renders the admin-only user access editor window.
 *
 * The editor deliberately separates selecting role or permission values from
 * saving them. Admins can click through choices in this window, but the server is
 * contacted only when they press Save.
 *
 * @param props - Access editor props.
 * @param props.editor - Current editor draft state.
 * @param props.error - Optional save error returned by the admin API.
 * @param props.saving - Whether the current editor row is being saved.
 * @param props.onChange - Callback for updating draft editor state.
 * @param props.onClose - Callback invoked when the editor is dismissed.
 * @param props.onSave - Callback invoked by the Save button.
 * @returns The dynamic role and permission editor window.
 */
function AdminUserAccessEditor({
  editor,
  error,
  saving,
  onChange,
  onClose,
  onSave,
}: {
  editor: AccessEditorState
  error: string | null
  saving: boolean
  onChange: (nextEditor: AccessEditorState) => void
  onClose: () => void
  onSave: () => void
}) {
  const title =
    editor.mode === "add" ? "Add employee access" : "Edit employee access"
  const dialogRef = useDialogFocus(onClose, !saving)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3 sm:p-6">
      <section
        ref={dialogRef}
        tabIndex={-1}
        aria-label={title}
        aria-modal="true"
        role="dialog"
        className="flex max-h-[calc(100dvh-1.5rem)] w-full max-w-2xl flex-col overflow-hidden rounded-lg border border-slate-200 bg-white text-slate-950 shadow-2xl sm:max-h-[calc(100dvh-3rem)]"
      >
        <div className="flex items-start justify-between gap-4 border-b border-slate-200 bg-white px-4 py-3">
          <div>
            <div className="flex items-center gap-2">
              <Users className="size-4 text-blue-700" aria-hidden="true" />
              <h2 className="text-base font-semibold">{title}</h2>
            </div>
            <p className="mt-1 text-xs text-slate-600">
              Select the role and permission state, then click Save to apply the
              change.
            </p>
          </div>
          <Button
            type="button"
            variant="outline"
            size="icon-sm"
            className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
            onClick={onClose}
            disabled={saving}
            title="Close access editor"
          >
            <X className="size-4" aria-hidden="true" />
            <span className="sr-only">Close access editor</span>
          </Button>
        </div>

        <div className="grid min-h-0 gap-4 overflow-y-auto overscroll-contain p-4">
          <label className="text-xs font-medium text-slate-600">
            Employee email
            <input
              type="email"
              value={editor.email}
              onChange={(event) =>
                onChange({ ...editor, email: event.target.value })
              }
              placeholder="employee@company.com"
              disabled={editor.mode === "edit" || saving}
              className="mt-1 h-9 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-950 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 disabled:bg-slate-100 disabled:text-slate-500"
            />
          </label>

          <div>
            <p className="text-xs font-medium text-slate-600">Role</p>
            <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
              {manageableRoles.map((roleOption) => (
                <button
                  key={roleOption}
                  type="button"
                  onClick={() => onChange({ ...editor, role: roleOption })}
                  disabled={saving}
                  className={`rounded-md border px-3 py-2 text-sm font-medium capitalize transition ${
                    editor.role === roleOption
                      ? "border-blue-700 bg-blue-700 text-white"
                      : "border-slate-300 bg-white text-slate-700 hover:bg-slate-50"
                  }`}
                >
                  {roleOption}
                </button>
              ))}
            </div>
            <p className="mt-2 text-xs text-slate-500">
              {roleRights(editor.role).join(" · ")}
            </p>
          </div>

          <div>
            <p className="text-xs font-medium text-slate-600">
              Permission state
            </p>
            <div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-3">
              {manageableStatuses.map((statusOption) => (
                <button
                  key={statusOption}
                  type="button"
                  onClick={() =>
                    onChange({ ...editor, accessStatus: statusOption })
                  }
                  disabled={saving}
                  className={`rounded-md border px-3 py-2 text-sm font-medium capitalize transition ${
                    editor.accessStatus === statusOption
                      ? accessStatusClass(statusOption)
                      : "border-slate-300 bg-white text-slate-700 hover:bg-slate-50"
                  }`}
                >
                  {statusOption}
                </button>
              ))}
            </div>
          </div>

          <label className="text-xs font-medium text-slate-600">
            Administrator note
            <textarea
              value={editor.note}
              onChange={(event) =>
                onChange({ ...editor, note: event.target.value })
              }
              placeholder="Optional reason for this role or permission change"
              maxLength={500}
              disabled={saving}
              className="mt-1 min-h-24 w-full resize-y rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 disabled:bg-slate-100 disabled:text-slate-500"
            />
          </label>

          <fieldset className="grid gap-2">
            <legend className="mb-2 text-sm font-semibold">Control permissions</legend>
            {(Object.entries(permissionLabels) as [Permission,string][]).map(([permission,label]) => <label key={permission} className="flex items-center gap-2 text-sm">
              <input type="checkbox" disabled={saving} checked={resolvePermissions(editor.role,editor.permissions)[permission]} onChange={event => onChange({...editor,permissions:{...editor.permissions,[permission]:event.target.checked}})} />{label}
            </label>)}
            <Button variant="outline" disabled={saving} onClick={() => onChange({...editor,permissions:{}})}>Use role defaults</Button>
          </fieldset>

          {error && (
            <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              {error}
            </p>
          )}
        </div>

        <div className="flex shrink-0 flex-wrap justify-end gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3">
          <Button
            type="button"
            variant="outline"
            className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
            onClick={onClose}
            disabled={saving}
          >
            Cancel
          </Button>
          <Button
            type="button"
            className="bg-blue-700 text-white hover:bg-blue-800"
            onClick={onSave}
            disabled={saving || !editor.email.trim()}
          >
            <Save className="size-4" aria-hidden="true" />
            {saving ? "Saving..." : "Save"}
          </Button>
        </div>
      </section>
    </div>
  )
}

/**
 * Renders the full administrator activity window.
 *
 * This modal-style window stays inside the admin-only panel and presents a larger
 * audit-event set with detailed target, request, and metadata information. The
 * white surface is intentionally explicit so administrators can distinguish this
 * security review area from the rest of the app workspace.
 *
 * @param props - Activity window props.
 * @param props.events - Audit events to display.
 * @param props.error - Optional loading error.
 * @param props.loading - Whether extended audit events are loading.
 * @param props.onClose - Callback invoked when the window is dismissed.
 * @returns The admin-only full activity window.
 */
function AdminActivityWindow({
  events,
  error,
  loading,
  onClose,
}: {
  events: AdminAuditEvent[]
  error: string | null
  loading: boolean
  onClose: () => void
}) {
  const [selectedEvent, setSelectedEvent] = useState<AdminAuditEvent | null>(
    null,
  )
  const [showSecurity, setShowSecurity] = useState(false)
  const [expanded, setExpanded] = useState(false)
  const dialogRef = useDialogFocus(onClose)

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/60 p-3 sm:p-6">
      <section ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label="All app activity" className={`mx-auto flex h-[calc(100dvh-1.5rem)] min-h-0 max-h-[calc(100dvh-1.5rem)] max-w-full flex-col overflow-hidden rounded-lg border border-slate-200 bg-white text-slate-950 shadow-2xl sm:h-[80dvh] sm:min-h-80 sm:min-w-[min(640px,calc(100vw-3rem))] sm:max-h-[calc(100dvh-3rem)] ${expanded ? "w-full sm:!h-[calc(100dvh-3rem)]" : "w-full sm:w-[90%] sm:max-w-7xl sm:resize"}`}>
        <div className="flex shrink-0 items-start justify-between gap-4 border-b border-slate-200 bg-white px-4 py-3">
          <div>
            <div className="flex items-center gap-2">
              <Activity className="size-4 text-blue-700" aria-hidden="true" />
              <h2 className="text-base font-semibold">All app activity</h2>
              <Button variant="outline" onClick={() => setShowSecurity(true)}>Security risks</Button>
              <Button variant="outline" size="icon-sm" title={expanded ? "Restore window" : "Expand window"} aria-label={expanded ? "Restore window" : "Expand window"} onClick={() => setExpanded(!expanded)}>
                {expanded ? <Minimize2 className="size-4" /> : <Maximize2 className="size-4" />}
              </Button>
            </div>
            <p className="mt-1 text-xs text-slate-600">
              Full admin view of recent audited actions across entries, profiles,
              approvals, and deletions.
            </p>
          </div>
          <Button
            type="button"
            variant="outline"
            size="icon-sm"
            className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
            onClick={onClose}
            title="Close activity window"
          >
            <X className="size-4" aria-hidden="true" />
            <span className="sr-only">Close activity window</span>
          </Button>
        </div>

        {showSecurity && <SecurityRiskWindow onClose={() => setShowSecurity(false)} />}
        {loading || error ? (
          <div
            className={`m-4 rounded-lg border px-4 py-3 text-sm ${
              error
                ? "border-red-200 bg-red-50 text-red-700"
                : "border-slate-200 bg-slate-50 text-slate-600"
            }`}
            role={error ? "alert" : "status"}
          >
            {error ?? "Loading app activity..."}
          </div>
        ) : events.length === 0 ? (
          <div className="px-6 py-16 text-center">
            <p className="text-sm font-medium">No app activity recorded yet</p>
            <p className="mt-1 text-xs text-slate-600">
              Audited actions will appear here after users change app data.
            </p>
          </div>
        ) : (
          <div tabIndex={0} aria-label="Activity table" className="min-h-0 flex-1 overflow-auto overscroll-contain">
            <table className="w-full min-w-[1200px] border-collapse text-left text-sm">
              <thead className="sticky top-0 bg-white">
                <tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500">
                  <th className="px-4 py-2 font-medium">Time</th>
                  <th className="px-4 py-2 font-medium">Actor</th>
                  <th className="px-4 py-2 font-medium">Action</th>
                  <th className="px-4 py-2 font-medium">Target</th>
                  <th className="px-4 py-2 font-medium">User agent</th>
                  <th className="px-4 py-2 font-medium">Metadata</th>
                </tr>
              </thead>
              <tbody>
                {events.map((event) => (
                  <tr
                    key={event.id}
                    className={`cursor-pointer border-b border-slate-200 align-top outline-none last:border-0 hover:bg-blue-50 focus:bg-blue-50 ${
                      selectedEvent?.id === event.id ? "bg-blue-50" : ""
                    }`}
                    tabIndex={0}
                    onClick={() => setSelectedEvent(event)}
                    onKeyDown={(keyboardEvent) => {
                      if (
                        keyboardEvent.key === "Enter" ||
                        keyboardEvent.key === " "
                      ) {
                        keyboardEvent.preventDefault()
                        setSelectedEvent(event)
                      }
                    }}
                  >
                    <td className="px-4 py-3 text-xs text-slate-600">
                      {formatAdminDateTime(event.occurredAt)}
                    </td>
                    <td className="px-4 py-3 font-medium">{event.actorEmail}</td>
                    <td className="px-4 py-3">{formatAuditAction(event.action)}</td>
                    <td className="px-4 py-3 text-xs text-slate-600">
                      <p>{event.targetType}</p>
                      <p className="mt-1 break-all font-mono">
                        {event.targetId ?? "No target id"}
                      </p>
                    </td>
                    <td className="max-w-sm px-4 py-3 text-xs text-slate-600">
                      <span className="line-clamp-1">
                        {event.userAgent ?? "Unknown"}
                      </span>
                    </td>
                    <td className="max-w-xs px-4 py-3 text-xs text-slate-600">
                      <p className="truncate">{formatAuditMetadata(event)}</p>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {selectedEvent && (
          <AdminActivityEventDetails
            key={selectedEvent.id}
            event={selectedEvent}
            onClose={() => setSelectedEvent(null)}
          />
        )}
      </section>
    </div>
  )
}

/**
 * Renders full data and metadata for a selected audit activity event.
 *
 * The detail panel is intentionally read-only and white, matching the admin
 * activity window while exposing the complete event record needed for review.
 *
 * @param props - Detail panel props.
 * @param props.event - Selected audit event to inspect.
 * @param props.onClose - Callback invoked when the detail panel is dismissed.
 * @returns Selected audit event detail panel.
 */
function AdminActivityEventDetails({
  event,
  onClose,
}: {
  event: AdminAuditEvent
  onClose: () => void
}) {
  const details = [
    { label: "Event ID", value: event.id },
    { label: "Occurred", value: formatAdminDateTime(event.occurredAt) },
    { label: "Actor", value: event.actorEmail },
    { label: "Action", value: formatAuditAction(event.action) },
    { label: "Target type", value: event.targetType },
    { label: "Target ID", value: event.targetId ?? "No target id" },
    { label: "IP address", value: event.ipAddress ?? "Unknown" },
    { label: "User agent", value: event.userAgent ?? "Unknown" },
  ]

  return (
    <aside className="max-h-[40dvh] shrink-0 overflow-y-auto overscroll-contain border-t border-slate-200 bg-white p-4">
      <div className="sticky top-0 z-[1] mb-3 flex items-start justify-between gap-4 bg-white pb-2">
        <div>
          <h3 className="text-sm font-semibold">Activity detail</h3>
          <p className="mt-1 text-xs text-slate-600">
            {formatAuditAction(event.action)} by {event.actorEmail}
          </p>
        </div>
        <Button
          type="button"
          variant="outline"
          size="icon-sm"
          className="border-slate-300 bg-white text-slate-900 hover:bg-slate-50"
          onClick={onClose}
          title="Close detail"
        >
          <X className="size-4" aria-hidden="true" />
          <span className="sr-only">Close detail</span>
        </Button>
      </div>

      <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(320px,0.8fr)]">
        <dl className="grid gap-2 sm:grid-cols-2">
          {details.map((detail) => (
            <div
              key={detail.label}
              className="rounded-lg border border-slate-200 bg-slate-50 p-3"
            >
              <dt className="text-xs font-medium uppercase tracking-wide text-slate-500">
                {detail.label}
              </dt>
              <dd className="mt-1 break-words text-sm text-slate-900">
                {detail.value}
              </dd>
            </div>
          ))}
        </dl>

        <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
          <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
            Metadata
          </p>
          <pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-words rounded-md bg-white p-3 font-mono text-xs leading-relaxed text-slate-800">
            {formatAuditMetadataBlock(event)}
          </pre>
        </div>
      </div>
    </aside>
  )
}

/**
 * Renders a compact statistic for the admin directory header.
 *
 * @param props - Statistic props.
 * @param props.icon - Lucide icon component used beside the label.
 * @param props.label - Human-readable statistic label.
 * @param props.value - Numeric statistic value.
 * @returns Admin directory statistic tile.
 */
function AdminStat({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Users
  label: string
  value: number
}) {
  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-slate-950">
      <div className="flex items-center gap-2 text-xs text-slate-600">
        <Icon className="size-3.5" aria-hidden="true" />
        {label}
      </div>
      <p className="mt-1 font-mono text-lg font-semibold tabular-nums">
        {value}
      </p>
    </div>
  )
}

/**
 * Converts roles into a seniority rank for admin directory ordering.
 *
 * Admins appear first, then managers, employees, base users, and finally
 * observed accounts without an assigned role.
 *
 * @param role - Role to rank for directory sorting.
 * @returns Numeric seniority rank used for descending ordering.
 */
function roleSeniority(role: UserRole | "none") {
  if (role === "admin") return 4
  if (role === "manager") return 3
  if (role === "employee") return 2
  if (role === "user") return 1
  return 0
}

/**
 * Sorts admin directory rows from highest to lowest seniority.
 *
 * Rows with the same role are ordered alphabetically by email so the directory is
 * stable after saves, reloads, and API responses.
 *
 * @param users - Directory rows to order.
 * @returns A new array sorted by role seniority and email.
 */
function sortAdminDirectoryUsers(users: AdminDirectoryUser[]) {
  return [...users].sort((a, b) => {
    const seniorityDelta = roleSeniority(b.role) - roleSeniority(a.role)
    if (seniorityDelta !== 0) return seniorityDelta
    return a.email.localeCompare(b.email)
  })
}

/**
 * Returns the visible rights granted by a role.
 *
 * The labels are intentionally short so they can fit inside the admin directory
 * table while still making each role's practical permissions clear.
 *
 * @param role - Role assigned to the user.
 * @returns Human-readable rights labels for the role.
 */
function roleRights(role: UserRole | "none") {
  if (role === "admin") {
    return ["all entries", "approvals", "reports", "users", "audit"]
  }
  if (role === "manager") {
    return ["team entries", "approvals", "reports"]
  }
  if (role === "employee") {
    return ["own entries", "submit time"]
  }
  if (role === "user") {
    return ["own entries", "submit time"]
  }
  return ["no assigned rights"]
}

/**
 * Returns the white-admin-table badge style for a user role.
 *
 * @param role - Role shown in the admin directory.
 * @returns Tailwind classes for the role badge.
 */
function roleBadgeClass(role: UserRole | "none") {
  if (role === "admin") {
    return "border-blue-200 bg-blue-50 text-blue-700"
  }
  if (role === "manager") {
    return "border-cyan-200 bg-cyan-50 text-cyan-700"
  }
  if (role === "employee") {
    return "border-green-200 bg-green-50 text-green-700"
  }
  if (role === "user") {
    return "border-slate-200 bg-slate-50 text-slate-700"
  }
  return "border-slate-200 bg-slate-100 text-slate-500"
}

/**
 * Returns the white-admin-table badge style for an access status.
 *
 * @param status - Access status shown in the admin directory.
 * @returns Tailwind classes for the status badge.
 */
function accessStatusClass(status: AccessStatus | "observed") {
  if (status === "active") {
    return "border-green-200 bg-green-50 text-green-700"
  }
  if (status === "denied") {
    return "border-amber-200 bg-amber-50 text-amber-700"
  }
  if (status === "blocked") {
    return "border-red-200 bg-red-50 text-red-700"
  }
  return "border-slate-200 bg-slate-100 text-slate-600"
}

/**
 * Formats an admin directory timestamp for compact table display.
 *
 * Invalid timestamps are returned unchanged so the admin can still see the raw
 * value instead of losing potentially useful diagnostic information.
 *
 * @param value - ISO timestamp returned by the user directory API.
 * @returns Localized date label or original value when parsing fails.
 */
function formatAdminDate(value: string) {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  })
}

/**
 * Formats an audit timestamp with date and time for investigation views.
 *
 * Invalid timestamps are returned unchanged so administrators can still inspect
 * raw values if an upstream data issue occurs.
 *
 * @param value - ISO timestamp returned by the audit API.
 * @returns Localized date-time label or original value when parsing fails.
 */
function formatAdminDateTime(value: string) {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}

/**
 * Converts a machine audit action into a readable label.
 *
 * @param action - Machine-readable audit action.
 * @returns Human-readable audit action label.
 */
function formatAuditAction(action: string) {
  return action.replaceAll("_", " ")
}

/**
 * Shortens long target identifiers for compact table display.
 *
 * Email targets are already readable, while UUID-like ids are shortened so the
 * audit table stays scannable on smaller screens.
 *
 * @param id - Target id from an audit event.
 * @returns Compact target id label.
 */
function shortId(id: string) {
  if (id.includes("@")) return id
  return id.length > 8 ? id.slice(0, 8) : id
}

/**
 * Formats sanitized audit metadata for admin table display.
 *
 * The metadata intentionally describes changed fields and workflow status rather
 * than full sensitive values. This keeps the security log informative but narrow.
 *
 * @param event - Audit event whose metadata should be summarized.
 * @returns Compact metadata summary.
 */
function formatAuditMetadata(event: AdminAuditEvent) {
  const parts: string[] = []
  const fields = event.metadata.changedFields
  const fromStatus = event.metadata.fromStatus
  const toStatus = event.metadata.toStatus

  if (typeof fromStatus === "string" && typeof toStatus === "string") {
    parts.push(`${fromStatus} to ${toStatus}`)
  }

  if (Array.isArray(fields) && fields.length > 0) {
    parts.push(`fields: ${fields.join(", ")}`)
  }

  const summary = parts.join(" · ") || `${Object.keys(event.metadata).length} metadata fields`
  return summary.length > 100 ? `${summary.slice(0, 97)}...` : summary
}

/**
 * Formats full audit metadata as readable JSON for the selected entry detail.
 *
 * The audit API already sanitizes metadata, so this formatter focuses on making
 * nested context easy to inspect in a fixed-width block.
 *
 * @param event - Audit event whose metadata should be rendered.
 * @returns Pretty-printed audit metadata.
 */
function formatAuditMetadataBlock(event: AdminAuditEvent) {
  return JSON.stringify(event.metadata, null, 2)
}
