/**
 * Defines shared application data shapes for entries and access roles.
 *
 * These types are imported by client components, API routes, and database helpers
 * so the app uses the same entry and role contracts across the stack.
 */
/**
 * Time entry persisted in Neon and rendered in the app UI.
 *
 * The id is generated by the database, while the remaining fields are either
 * parsed from notes or edited manually by the user.
 */
export type TimeEntry = {
  id: string
  contractor: string
  /** ISO date string: YYYY-MM-DD */
  date: string
  hours: number
  project: string
  description: string
}

/**
 * Shape returned by the AI parser before persistence.
 *
 * Parsed entries intentionally omit the database id because they are not durable
 * until the entries API stores them.
 */
export type ParsedEntry = Omit<TimeEntry, "id">

/**
 * Role names supported by the navigation and API access rules.
 *
 * Admins and managers can view team-wide data, while workers and users are scoped
 * to entries owned by their signed-in email.
 */
export type UserRole = "admin" | "manager" | "worker" | "user"
