/**
 * Defines shared application data shapes for entries, approvals, and access roles.
 *
 * These types are imported by client components, API routes, and database helpers
 * so the app uses the same entry and role contracts across the stack.
 */
/**
 * Approval states supported by the timesheet workflow.
 *
 * Draft entries are still being reviewed by the employee, submitted entries are
 * ready for manager review, approved entries are accepted for reporting, and
 * rejected entries need employee correction before resubmission.
 */
export type EntryStatus = "draft" | "submitted" | "approved" | "rejected"

/**
 * Time entry persisted in Neon and rendered in the app UI.
 *
 * The id is generated by the database, core work fields are parsed or edited by
 * the user, and approval fields track the manager review lifecycle.
 */
export type TimeEntry = {
  id: string
  /** Server-assigned record owner; never inferred from the display contractor name. */
  ownerEmail?: string
  contractor: string
  /** ISO date string: YYYY-MM-DD */
  date: string
  hours: number
  project: string
  description: string
  status: EntryStatus
  reviewedBy?: string | null
  reviewedAt?: string | null
  reviewNote?: string | null
}

/**
 * Shape returned by the AI parser before persistence.
 *
 * Parsed entries intentionally omit the database id because they are not durable
 * until the entries API stores them.
 */
export type ParsedEntry = Omit<
  TimeEntry,
  "id" | "ownerEmail" | "status" | "reviewedBy" | "reviewedAt" | "reviewNote"
>

/**
 * Role names supported by the navigation and API access rules.
 *
 * Admins and managers can view team-wide data, while employees and users are
 * scoped to entries owned by their signed-in email.
 */
export type UserRole = "admin" | "manager" | "account_manager" | "employee" | "contractor"

/**
 * Access states administrators can apply to managed app users.
 *
 * Active users can enter the app with their assigned role. Denied users are known
 * but not currently approved, while blocked users are explicitly barred until an
 * administrator changes their status.
 */
export type AccessStatus = "active" | "denied" | "blocked"
